# For Github User
# github_username: "slack_member_id"

thecadams: U016T2173B8
IvanBuljovcic: U01FPLZ0Y8Y
denisdimitrov: U01F6153AFN
0xdevalias: U01EC2DTD8F
# For Github Team
# github_teamname: "slack_member_id"
