# For Github User
# github_username: "slack_member_id"

thecadams: "Chris Adams"
IvanBuljovcic: "Ivan Buljovcic"
denisdimitrov: "Denis Dimitrov"
0xdevalias: "devalias"

# For Github Team
# github_teamname: "slack_member_id"
