version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cp ./src/secrets.dist.js ./src/secrets.js
            - run: npm install
            - run: npm run init
            - run: npm run build
            # - run: npm test
  deploy-functions:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd functions && npm i
            - run: ./node_modules/.bin/firebase use staging --token "$FIREBASE_TOKEN"
            - run: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"
workflows:
    build-test-deploy:
      jobs:
        - build-and-test
        - deploy-functions:
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - feature/cd
