version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run init
            - run: npm run lint
            # - run: npm test
  deploy-functions:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd functions && npm i
            - run:
                command: |
                  if [ $CIRCLE_BRANCH = "staging" ]; then
                    ENV=staging
                  fi
                  if [ $CIRCLE_BRANCH = "master" ]; then
                    ENV=prod
                  fi
                  ./node_modules/.bin/firebase use $ENV --token "$FIREBASE_TOKEN"
            - run: ./node_modules/.bin/firebase deploy --only functions --token "$FIREBASE_TOKEN"
  deploy-hosting:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                command: |
                  if [ $CIRCLE_BRANCH = "staging" ]; then
                    PREFIX=STAGING_
                  fi
                  if [ $CIRCLE_BRANCH = "master" ]; then
                    PREFIX=PROD_
                  fi
                  ./scripts/init-env.sh $PREFIX
            - run: npm run build
            - run:
                command: |
                  if [ $CIRCLE_BRANCH = "staging" ]; then
                    ENV=staging
                  fi
                  if [ $CIRCLE_BRANCH = "master" ]; then
                    ENV=prod
                  fi
                  ./node_modules/.bin/firebase use $ENV --token "$FIREBASE_TOKEN"
            - run:
                command: |
                  if [ $CIRCLE_BRANCH = "staging" ]; then
                    TARGET=staging
                  fi
                  if [ $CIRCLE_BRANCH = "master" ]; then
                    TARGET=co-reality-map
                  fi
                  ./node_modules/.bin/firebase deploy --only hosting:$TARGET --token "$FIREBASE_TOKEN"
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy-functions:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
      - deploy-hosting:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
